version: "3.3"

services:
  elasticsearch:
    build:
      context: images/elasticsearch
    volumes:
      - ./volumes/esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    build:
      context: images/kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    volumes:
      - ./volumes/kfdata:/kafka
    links:
      - zookeeper
    environment:
      # Во внутренней сети docker-compose слушаем адрес kafka:9092
      # Из внешней сети docker-compose будем слушать localhost:9094
      # Как альтерантива, можно вычислять адрес как-то так:
      # HOSTNAME_COMMAND: curl http://169.254.169.254/latest/meta-data/public-hostname
      # KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  logstash:
    build:
      context: images/logstash
    ports:
      - "5044:5044"
      - "1111:1111"
    depends_on:
      - kafka
      - elasticsearch
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
    links:
      - elasticsearch
#      - kafka
#      - zookeeper

#  kafdrop:
#    image: obsidiandynamics/kafdrop:3.27.0
#    ports:
#      - "9000:9000"
#    depends_on:
#      - kafka
#    environment:
#      KAFKA_BROKERCONNECT: "kafka:9092"
#    links:
#      - elasticsearch
